### ISSUE TITLE
Issue regarding non 1:1 images and higer resolutions

### ISSUE THREAD

**Issue by CounterFlow64** [cyclomon/CLIPstyler#6]
First I must say, this tool is pure magic! Thanks for developing it.

I see that in the research paper, there is a demonstration image which gets style-transferred to its original format, which was a non-square, it was a image of a field and skies. I also never got any image output over the resolution of 512, which my 24GB card would surely handle.

I tried settings the --crop_size, --num_crop and --image_size options, but it never did anything. I'm no programmer (and still have a github lol, I want to learn rust eventually) and I looked through the various .py files, but couldn't find anything obvious to change it.

Is there not any way to change this in the released model, or did I just miss something?

**Comment by cyclomon** [comment]
I revised the training code. You can use content image with arbitrary resolution.
Please set the resolution sizes with --img_width , --img_height   arguments.
Note that resolution sizes must be multiple of 8, since our network has 3 downsample and 3 upsample blocks.
