### ISSUE TITLE
about clip_model ‘ViT-B/32’

### ISSUE THREAD

**Issue by yanmingqiang** [cyclomon/CLIPstyler#7]
Hi, I recently saw your work intrigued, but trying to run your training code got the following problem, can you give me a hint?
![image](https://user-images.githubusercontent.com/90613627/164722748-8d7f28fc-863f-40d9-aa09-dce6ed4b3a1c.png)

**Comment by cyclomon** [comment]
Maybe there are some environment problems.
Please refer to this link
[https://github.com/openai/CLIP/issues/180](https://github.com/openai/CLIP/issues/180)
