### ISSUE TITLE
NameError: name 'net' is not defined

### ISSUE THREAD

**Issue by xunings** [cyclomon/CLIPstyler#9]
Hi,
I got the following error while testing the fast style transfer model,

```
Traceback (most recent call last):
  File "test_fast.py", line 76, in <module>
    network = net.Net(vgg, decoder)
NameError: name 'net' is not define
```

Seems that `net.Net` should be `fast_stylenet.Net` in https://github.com/cyclomon/CLIPstyler/blob/c8ba7a088b566d40dea3771bc298c08189123eca/test_fast.py#L76

There seems to be another typo that `--content_path` should be changed to `--content_dir` in README for train_fast.py

https://github.com/cyclomon/CLIPstyler/blob/main/README.md#fast-style-transfer

**Comment by cyclomon** [comment]
Thank you!  I corrected the typos.
